### ISSUE TITLE
docker build fails when trying to add `out`

### ISSUE THREAD

**Issue by elmiko** [openshift-evangelists/openshifter-java#1]
i am trying to utilize this the image created by this project and i am having trouble creating the image. it appears that the dockerfile expends a file name `out` that is not present, this causes the image creation to fail in step 10.

## steps to reproduce

1. clone repository
1. run `docker build -t openshifter-java .` in repository directory

## output

this is a snippet from the end of the output from running the command from above
```
Step 6 : WORKDIR /root
 ---> Running in c496013f6ec2
 ---> 388dd732e282
Removing intermediate container c496013f6ec2
Step 7 : RUN git clone https://github.com/openshift/openshift-ansible.git
 ---> Running in 1cf934f143c7
Cloning into 'openshift-ansible'...
 ---> 5b7aab1b76a2
Removing intermediate container 1cf934f143c7
Step 8 : RUN cd openshift-ansible && git checkout release-1.4 && cd ..
 ---> Running in f8b356711c73
Switched to a new branch 'release-1.4'
Branch release-1.4 set up to track remote branch release-1.4 from origin.
 ---> 5bc3ef4731f6
Removing intermediate container f8b356711c73
Step 9 : ENV OPENSHIFT_ANSIBLE /root/openshift-ansible
 ---> Running in 387489f88b9a
 ---> 40fb7b66e7d8
Removing intermediate container 387489f88b9a
Step 10 : ADD out /root/
lstat out: no such file or directory
```

## suggested fix

either the `out` file should be added to the repository, or there should be more instructions about how to create the image.

**Comment by elmiko** [comment]
@marekjelen ptal

**Comment by marekjelen** [comment]
The out is a result of maven build

```
#!/usr/bin/env bash

mvn -P release clean package

docker build . -t openshifter
```

**Comment by elmiko** [comment]
excellent, thanks Marek!

i will put up a pr to the readme describing this
